name: 'Generate Calico Manifest'
description: 'Generates a Calico manifest for NetworkSet from CIDR files'
author: 'Pål Sollie <sollie@sparkz.no>'
version: 'v1'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  name:
    required: true
    description: 'Name of the NetworkSet'
  namespace:
    required: true
    description: 'Namespace of the NetworkSet'
  labels:
    required: true
    description: 'YAML list of maps for labels in key:value format'
  file-paths:
    required: true
    description: 'Paths to the files containing CIDRs'
